@startuml
'https://plantuml.com/class-diagram

Interferencia <|-left-  Piquete
Interferencia <|-up-  Pozo
Interferencia <|-up-  ControlPolicial
Interferencia <|-up-  SorpresaFavorable
Interferencia <|-down-  SorpresaDesfavorable
Interferencia <|-down-  SorpresaCambioVehiculo

Juego "1" --> "1" Mapa
Juego "1" -left-> "1" Random
Mapa "1" --> "1" Random
Mapa "1" --> "1" Vehiculo
Mapa "1" --> "1" Meta
Mapa "1" --> "*" Interferencia
Vehiculo "1" --> "1" TipoVehiculo
Interferencia "1" -right-> "1" Coordenadas

TipoVehiculo <|-- Moto
TipoVehiculo <|-- Auto
TipoVehiculo <|-left- CuatroXCuatro

@enduml